#pragma once

#define PCO_CONTROLLER_NAMESPACE            pco_controller
#define BEGIN_PCO_CONTROLLER_NAMESPACE      namespace PCO_CONTROLLER_NAMESPACE {
#define END_PCO_CONTROLLER_NAMESPACE        }

BEGIN_PCO_CONTROLLER_NAMESPACE

END_PCO_CONTROLLER_NAMESPACE
