#pragma once

#define PCO_INTERFACES_NAMESPACE            pco_interfaces
#define BEGIN_PCO_INTERFACES_NAMESPACE      namespace PCO_INTERFACES_NAMESPACE {
#define END_PCO_INTERFACES_NAMESPACE        }

BEGIN_PCO_INTERFACES_NAMESPACE

END_PCO_INTERFACES_NAMESPACE
