#pragma once

#define PCO_COMMON_NAMESPACE            pco_common
#define BEGIN_PCO_COMMON_NAMESPACE      namespace PCO_COMMON_NAMESPACE {
#define END_PCO_COMMON_NAMESPACE        }

BEGIN_PCO_COMMON_NAMESPACE

END_PCO_COMMON_NAMESPACE
